# Generated by Django 3.1.2 on 2020-10-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('date_re', models.DateField()),
                ('department', models.CharField(max_length=20)),
            ],
        ),
    ]
